spring:
  banner:
    location: classpath:/bannerSpring.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/develop18  
    data-username:  develop
    data-password:  develop 
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
   
      